models/User.php
<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property integer $isAdmin
 * @property string $photo
 *
 * @property Order[] $comments
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['isAdmin'], 'integer'],
            [['name', 'email', 'password', 'photo'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'email' => 'Email',
            'password' => 'Пароль',
            'isAdmin' => 'Админ?',
            'photo' => 'Фото',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['user_id' => 'id']);
    }

    public static function findIdentity($id)
    {
        return User::findOne($id);
    }
    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        // TODO: Implement getAuthKey() method.
    }

    public function validateAuthKey($authKey)
    {
        // TODO: Implement validateAuthKey() method.
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    public static function findByEmail($email)
    {
        return User::find()->where(['email'=>$email])->one();
    }

    public function validatePassword($password)
    {
        return ($this->password == $password) ? true : false;
    }
    
    public function create()
    {
        return $this->save(false);
    }

    public function getImage()
    {
        return $this->photo;
    }
}

controllers/AuthController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\SignupForm;
use app\models\User;
use Yii;
use yii\web\Controller;

class AuthController extends Controller
{

	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		}
		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout()
	{
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function actionSignup()
	{
		$model = new SignupForm();

		if(Yii::$app->request->isPost)
		{
			$model->load(Yii::$app->request->post());
			if($model->signup())
			{
				return $this->redirect(['auth/login']);
			}
		}

		return $this->render('signup', ['model'=>$model]);
	}

	public function actionTest()
	{
		$user = User::findOne(1);

		Yii::$app->user->logout();
		
		if(Yii::$app->user->isGuest)
		{
			echo 'Пользователь гость';
		}
		else
		{
			echo 'Пользователь Авторизован';
		}
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Project;

use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Order;

class SiteController extends Controller {

	public function behaviors() {
		return [];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function actionIndex() {
		$data = Project::getAll(12);

		return $this->render('index',[
			'projects'=>$data['projects'],
		]);
	}

	public function actionProjects($id = null) {
		$data = Project::getAll(12);
		$recent = Project::getRecent();
		// $popular = Project::getPopular();

		return $this->render('projects',[
			'projects'=>$data['projects'],
			'pagination'=>$data['pagination'],
			'recent'=>$recent,
		]);
	}

	public function actionView($id) {

		$project = Project::findOne($id);
		// $popular = Project::getPopular();
		$recent = Project::getRecent();
		$order = new Order();

		$project->viewedCounter();
		
		if(Yii::$app->request->isPost && !Yii::$app->user->isGuest){

			$order->load(Yii::$app->request->post());

			$order->user_id = Yii::$app->user->id;

			$order->email = Yii::$app->request->post()['Order']['email'];
			$order->phone = Yii::$app->request->post()['Order']['phone'];

			$order->project_id = $project->id;
			$order->date = date('Y-m-d');

			$order->save();

			return $this->redirect(['site/view','id'=>$id]);
		}

		return $this->render('single',[
			'project'=>$project,
			'recent'=>$recent,
			'categories'=>$categories,
			'order'=>$order,
		]);
	}

}

views/partials/comment.php
<?php if(!empty($comments)):?>

    <?php foreach($comments as $comment):?>
        <div class="bottom-comment"><!--bottom comment-->
            <div class="comment-img">
                <img width="50" class="img-circle" src="<?= $comment->user->image; ?>" alt="">
            </div>

            <div class="comment-text">
                <a href="#" class="replay btn pull-right"> Replay</a>
                <h5><?= $comment->user->name;?></h5>

                <p class="comment-date">
                    <?= $comment->getDate();?>
                </p>


                <p class="para"><?= $comment->text; ?></p>
            </div>
        </div>
    <?php endforeach;?>

<?php endif;?>
<!-- end bottom comment-->

<?php if(!Yii::$app->user->isGuest):?>
    <div class="leave-comment"><!--leave comment-->
        <h4>Leave a reply</h4>
        <?php if(Yii::$app->session->getFlash('comment')):?>
            <div class="alert alert-success" role="alert">
                <?= Yii::$app->session->getFlash('comment'); ?>
            </div>
        <?php endif;?>
        <?php $form = \yii\widgets\ActiveForm::begin([
            'action'=>['site/comment', 'id'=>$article->id],
            'options'=>['class'=>'form-horizontal contact-form', 'role'=>'form']])?>
        <div class="form-group">
            <div class="col-md-12">
                <?= $form->field($commentForm, 'comment')->textarea(['class'=>'form-control','placeholder'=>'Write Message'])->label(false)?>
            </div>
        </div>
        <button type="submit" class="btn send-btn">Post Comment</button>
        <?php \yii\widgets\ActiveForm::end();?>
    </div><!--end leave comment-->
<?php endif;?>

views/partials/footer.php
<div class="footer">
	<div class="container">
			<p class="copyright">Copyright 2013. All rights reserved.	</p>
	</div>
</div>

<!-- Modal -->
<div id="loginpop" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="row">
				<div class="col-sm-6 login">
					<h4>Login</h4>
					<form class="" role="form">
						<div class="form-group">
							<label class="sr-only" for="exampleInputEmail2">Email address</label>
							<input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
						</div>
						<div class="form-group">
							<label class="sr-only" for="exampleInputPassword2">Password</label>
							<input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox"> Remember me
							</label>
						</div>
						<button type="submit" class="btn btn-success">Sign in</button>
					</form>          
				</div>
				<div class="col-sm-6">
					<h4>New User Sign Up</h4>
					<p>Join today and get updated with all the properties deal happening around.</p>
					<button type="submit" class="btn btn-info"  onclick="window.location.href='register.php'">Join Now</button>
				</div>

			</div>
		</div>
	</div>
</div>
<!-- /.modal -->

</body>
</html>

views/partials/header.php
<?php
use yii\helpers\Url;
?>
<!-- Header Starts -->
<div class="navbar-wrapper">

        <div class="navbar-inverse" role="navigation">
          <div class="container">
            <div class="navbar-header">


              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>


            <!-- Nav Starts -->
            <div class="navbar-collapse  collapse">
              <ul class="nav navbar-nav navbar-right">
              	<li class=""><a href="<?= Url::toRoute(['/']) ?>">Главная</a></li>
								<li class=""><a href="<?= Url::toRoute(['/site/projects']) ?>">Продажа</a></li>
              	<?php if(Yii::$app->user->isGuest):?>
              		<li><a href="<?= Url::toRoute(['/auth/login'])?>">Вход</a></li>
              		<li><a href="<?= Url::toRoute(['/auth/signup'])?>">Регистрация</a></li>
              	<?php else: ?>
              		<?php if(Yii::$app->user->identity->isAdmin && false): ?>
              			<li><a href="<?= Url::toRoute(['/admin'])?>">Админка</a></li>
              		<?php endif ?>
              		<li><a href="<?= Url::toRoute(['/user/my-projects'])?>">Мои обьявления</a></li>
              		<li><a href="<?= Url::toRoute(['/auth/logout'])?>">Выход <?= ' (' . Yii::$app->user->identity->name . ')' ?></a></li>
              	<?php endif;?>
              </ul>
            </div>
            <!-- #Nav Ends -->

          </div>
        </div>

    </div>
<!-- #Header Starts -->

<div class="container">

<!-- Header Starts -->
<div class="header">
<a href="<?= Url::toRoute(['/']) ?>"><img src="/public/images/logo.png" alt="Logo"></a>
</div>
<!-- #Header Starts -->
</div>

views/partials/item.php
<?php
use yii\helpers\Url;
?>
<?php foreach($projects as $project):?>
	<article class="post_type_4">
		<div class="feature">
			<div class="image">
				<a href="<?= Url::toRoute(['site/view', 'id'=>$project->id]);?>">
					<img class="item-img" src="<?= $project->getImage();?>" alt=""><span class="hover"></span>
				</a>
			</div>
		</div>
		
		<div class="content">
			<div class="info">
				<div class="date"><?= $project->getDate();?></div>
				<div class="stats">
					<div class="views"><?= (int)$project->viewed ?></div>
				</div>
			</div>
			
			<div class="title">
				<a href="<?= Url::toRoute(['site/view', 'id'=>$project->id]);?>"><?= $project->title ?></a>
			</div>
			
			<div class="line_1"></div>
		</div>
	</article>
<?php endforeach; ?>

views/partials/sidebar.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="hot-properties hidden-xs">
	<h4>Новинки</h4>
	<?php foreach($projects as $item):?>
	<div class="row">
		<div class="col-lg-4 col-sm-5"><img src="<?= $item->getImage() ?>" class="img-responsive img-circle" alt="properties"></div>
		<div class="col-lg-8 col-sm-7">
			<h5><a href="<?= Url::toRoute(['site/view', 'id'=>$item->id]);?>"><?= $item->title ?></a></h5>
			<p class="price">$<?= $item->price ?></p>
		</div>
	</div>
	<?php endforeach ?>
</div>